//! First-run initialization.
//!
//! New installations deliberately start in official-login mode for both Claude
//! applications. Third-party providers are only added explicitly by the user or
//! through the per-application import action.

use rusqlite::{params, params_from_iter};

use crate::error::AppResult;

/// The catalog is intentionally embedded in the release: it never calls a
/// third party service and only inserts models that are not already present.
/// Updating an application therefore cannot overwrite a user-modified price.
/// Anthropic cache_write uses the 5-minute cache-write rate; cache_read is hit rate.
pub(crate) const CATALOG_VERSION: &str = "2026-09-04";

struct DefaultPricing {
    provider: &'static str,
    model: &'static str,
    input: f64,
    cache_read: f64,
    cache_write: f64,
    output: f64,
    batch_input: f64,
    batch_output: f64,
    currency: &'static str,
    source_url: &'static str,
}

const DEFAULT_PRICING: &[DefaultPricing] = &[
    // OpenAI standard pricing checked 2026-09-04. `*-fast` rows use Fast mode.
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-6-astra",
        input: 10.0,
        cache_read: 1.0,
        cache_write: 12.5,
        output: 50.0,
        batch_input: 5.0,
        batch_output: 25.0,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-6-astra-fast",
        input: 20.0,
        cache_read: 2.0,
        cache_write: 25.0,
        output: 100.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.5",
        input: 5.0,
        cache_read: 0.5,
        cache_write: 0.0,
        output: 30.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://openai.com/api/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.6-sol",
        input: 4.0,
        cache_read: 0.4,
        cache_write: 5.0,
        output: 20.0,
        batch_input: 2.0,
        batch_output: 10.0,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.6-sol-fast",
        input: 8.0,
        cache_read: 0.8,
        cache_write: 10.0,
        output: 40.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.4",
        input: 2.5,
        cache_read: 0.25,
        cache_write: 0.0,
        output: 15.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://openai.com/api/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.6-terra",
        input: 2.0,
        cache_read: 0.2,
        cache_write: 2.5,
        output: 12.0,
        batch_input: 1.0,
        batch_output: 6.0,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.6-luna",
        input: 0.2,
        cache_read: 0.02,
        cache_write: 0.25,
        output: 1.2,
        batch_input: 0.1,
        batch_output: 0.6,
        currency: "USD",
        source_url: "https://developers.openai.com/api/docs/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5-mini",
        input: 0.25,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 2.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://openai.com/api/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.4-mini",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 4.5,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://openai.com/api/pricing/",
    },
    DefaultPricing {
        provider: "OpenAI",
        model: "gpt-5.4-nano",
        input: 0.2,
        cache_read: 0.02,
        cache_write: 0.0,
        output: 1.25,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://openai.com/api/pricing/",
    },
    // Anthropic pricing checked 2026-09-04. Cache write is the 5-minute rate.
    // Fable 5.1 is the exception to the usual 10% cache-read rule ($0.25/MTok).
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-fable-5",
        input: 10.0,
        cache_read: 1.0,
        cache_write: 12.5,
        output: 50.0,
        batch_input: 5.0,
        batch_output: 25.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    // Fable 5.1 (2026-09-01): 1M context / 128K output.
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-fable-5.1",
        input: 10.0,
        cache_read: 0.25,
        cache_write: 12.5,
        output: 50.0,
        batch_input: 5.0,
        batch_output: 25.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-mythos-5.1",
        input: 5.0,
        cache_read: 0.5,
        cache_write: 6.25,
        output: 25.0,
        batch_input: 2.5,
        batch_output: 12.5,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-opus-4.8",
        input: 5.0,
        cache_read: 0.5,
        cache_write: 6.25,
        output: 25.0,
        batch_input: 2.5,
        batch_output: 12.5,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-opus-4.8-fast",
        input: 10.0,
        cache_read: 1.0,
        cache_write: 12.5,
        output: 50.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-opus-5",
        input: 5.0,
        cache_read: 0.5,
        cache_write: 6.25,
        output: 25.0,
        batch_input: 2.5,
        batch_output: 12.5,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-opus-5-fast",
        input: 10.0,
        cache_read: 1.0,
        cache_write: 12.5,
        output: 50.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-sonnet-4.6",
        input: 3.0,
        cache_read: 0.3,
        cache_write: 3.75,
        output: 15.0,
        batch_input: 1.5,
        batch_output: 7.5,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-sonnet-5",
        input: 2.0,
        cache_read: 0.2,
        cache_write: 2.5,
        output: 10.0,
        batch_input: 1.0,
        batch_output: 5.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Anthropic",
        model: "claude-haiku-4.5",
        input: 1.0,
        cache_read: 0.1,
        cache_write: 1.25,
        output: 5.0,
        batch_input: 0.5,
        batch_output: 2.5,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.1-pro",
        input: 2.0,
        cache_read: 0.2,
        cache_write: 0.0,
        output: 12.0,
        batch_input: 1.0,
        batch_output: 6.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    // Gemini 3.8/3.7/3.6 Flash promotional pricing is active through 2026-10-01.
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.8-flash",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.375,
        batch_output: 1.875,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.7-flash",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.375,
        batch_output: 1.875,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.6-flash",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.375,
        batch_output: 1.875,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.5-flash",
        input: 1.5,
        cache_read: 0.15,
        cache_write: 0.0,
        output: 9.0,
        batch_input: 0.75,
        batch_output: 4.5,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-3.5-flash-lite",
        input: 0.3,
        cache_read: 0.03,
        cache_write: 0.0,
        output: 2.5,
        batch_input: 0.15,
        batch_output: 1.25,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Google",
        model: "gemini-2.5-flash-lite",
        input: 0.1,
        cache_read: 0.01,
        cache_write: 0.0,
        output: 0.4,
        batch_input: 0.05,
        batch_output: 0.2,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-chat",
        input: 2.0,
        cache_read: 0.5,
        cache_write: 0.0,
        output: 8.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-reasoner",
        input: 4.0,
        cache_read: 1.0,
        cache_write: 0.0,
        output: 16.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-v3",
        input: 2.0,
        cache_read: 0.5,
        cache_write: 0.0,
        output: 8.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-r1",
        input: 4.0,
        cache_read: 1.0,
        cache_write: 0.0,
        output: 16.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    // DeepSeek has weekday off-peak discounts; defaults use the peak rate so
    // estimates do not understate requests made outside the discount window.
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-v4-pro",
        input: 1.32,
        cache_read: 0.044,
        cache_write: 0.0,
        output: 3.96,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    DefaultPricing {
        provider: "DeepSeek",
        model: "deepseek-v4-flash",
        input: 0.44,
        cache_read: 0.014,
        cache_write: 0.0,
        output: 1.32,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://api-docs.deepseek.com/quick_start/pricing",
    },
    // Alibaba Cloud China (Beijing), using each model's lowest context tier.
    DefaultPricing {
        provider: "Alibaba Qwen",
        model: "qwen3.8-max",
        input: 12.0,
        cache_read: 1.5,
        cache_write: 15.0,
        output: 36.0,
        batch_input: 6.0,
        batch_output: 18.0,
        currency: "CNY",
        source_url: "https://help.aliyun.com/zh/model-studio/qwen3-8-max",
    },
    DefaultPricing {
        provider: "Alibaba Qwen",
        model: "qwen3.7-max",
        input: 6.0,
        cache_read: 2.4,
        cache_write: 15.0,
        output: 18.0,
        batch_input: 3.0,
        batch_output: 9.0,
        currency: "CNY",
        source_url: "https://help.aliyun.com/zh/model-studio/models",
    },
    DefaultPricing {
        provider: "Alibaba Qwen",
        model: "qwen3.7-plus",
        input: 1.6,
        cache_read: 0.4,
        cache_write: 2.5,
        output: 6.4,
        batch_input: 0.8,
        batch_output: 3.2,
        currency: "CNY",
        source_url: "https://help.aliyun.com/zh/model-studio/qwen3-7-plus",
    },
    DefaultPricing {
        provider: "Alibaba Qwen",
        model: "qwen3.6-plus",
        input: 2.0,
        cache_read: 0.2,
        cache_write: 2.5,
        output: 12.0,
        batch_input: 1.0,
        batch_output: 6.0,
        currency: "CNY",
        source_url: "https://help.aliyun.com/zh/model-studio/qwen3-6-plus",
    },
    DefaultPricing {
        provider: "ByteDance Doubao",
        model: "doubao-seed-2.1-pro",
        input: 6.0,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 30.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://www.volcengine.com/docs/82379",
    },
    DefaultPricing {
        provider: "Zhipu GLM",
        model: "glm-5.2",
        input: 8.0,
        cache_read: 2.0,
        cache_write: 0.0,
        output: 28.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://docs.bigmodel.cn/cn/guide/models/text/glm-5.2",
    },
    DefaultPricing {
        provider: "Zhipu GLM",
        model: "glm-5.1",
        input: 6.0,
        cache_read: 1.3,
        cache_write: 0.0,
        output: 24.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://open.bigmodel.cn/pricing",
    },
    // Kimi China API: caching is automatic and has no separate write fee.
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "kimi-k3",
        input: 20.0,
        cache_read: 2.0,
        cache_write: 0.0,
        output: 100.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "k3",
        input: 20.0,
        cache_read: 2.0,
        cache_write: 0.0,
        output: 100.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "k3-256k",
        input: 20.0,
        cache_read: 2.0,
        cache_write: 0.0,
        output: 100.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "kimi-k2.6",
        input: 6.5,
        cache_read: 1.1,
        cache_write: 0.0,
        output: 27.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "k2.6",
        input: 6.5,
        cache_read: 1.1,
        cache_write: 0.0,
        output: 27.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    DefaultPricing {
        provider: "Moonshot/Kimi",
        model: "kimi-k2.7-code",
        input: 6.5,
        cache_read: 1.3,
        cache_write: 0.0,
        output: 27.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "CNY",
        source_url: "https://platform.kimi.com/docs/pricing/chat",
    },
    // MiniMax international pay-as-you-go rate for contexts up to 200K.
    DefaultPricing {
        provider: "MiniMax",
        model: "minimax-m3",
        input: 0.3,
        cache_read: 0.03,
        cache_write: 0.375,
        output: 1.2,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.minimax.io/docs/guides/pricing-paygo",
    },
    DefaultPricing {
        provider: "xAI",
        model: "grok-4.6",
        input: 2.0,
        cache_read: 0.5,
        cache_write: 0.0,
        output: 6.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.x.ai/developers/models/grok-4-6",
    },
    DefaultPricing {
        provider: "xAI",
        model: "grok-4.3",
        input: 1.25,
        cache_read: 0.31,
        cache_write: 0.0,
        output: 2.5,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.x.ai/developers/models/grok-4-3",
    },
    DefaultPricing {
        provider: "xAI",
        model: "grok-4.1-fast",
        input: 0.2,
        cache_read: 0.05,
        cache_write: 0.0,
        output: 0.5,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.x.ai/developers/models",
    },
    DefaultPricing {
        provider: "xAI",
        model: "grok-build-0.1",
        input: 2.0,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 6.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.x.ai/developers/models",
    },
    DefaultPricing {
        provider: "Mistral",
        model: "mistral-medium-3.5",
        input: 0.4,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 2.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.mistral.ai/getting-started/models/models_overview/",
    },
    DefaultPricing {
        provider: "Mistral",
        model: "mistral-large-3",
        input: 0.5,
        cache_read: 0.05,
        cache_write: 0.0,
        output: 1.5,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.mistral.ai/getting-started/models/models_overview/",
    },
    DefaultPricing {
        provider: "Mistral",
        model: "mistral-small-4",
        input: 0.15,
        cache_read: 0.015,
        cache_write: 0.0,
        output: 0.6,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://docs.mistral.ai/getting-started/models/models_overview/",
    },
    // Antigravity gateway public model ids (subscription traffic; rates mirror public API list for estimates).
    DefaultPricing {
        provider: "Antigravity",
        model: "claude-sonnet-4-6",
        input: 3.0,
        cache_read: 0.3,
        cache_write: 3.75,
        output: 15.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "claude-sonnet-4-6-thinking",
        input: 3.0,
        cache_read: 0.3,
        cache_write: 3.75,
        output: 15.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "claude-opus-4-6-thinking",
        input: 5.0,
        cache_read: 0.5,
        cache_write: 6.25,
        output: 25.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.8-flash-high",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.8-flash-medium",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.8-flash-low",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.7-flash-high",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.7-flash-medium",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.7-flash-low",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.6-flash-high",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.6-flash-low",
        input: 0.75,
        cache_read: 0.075,
        cache_write: 0.0,
        output: 3.75,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3-flash",
        input: 0.5,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 3.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3-flash-agent",
        input: 0.5,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 3.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3-pro-high",
        input: 2.0,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 12.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.1-pro-high",
        input: 2.0,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 12.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-3.1-pro-low",
        input: 1.0,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 6.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-2.5-flash",
        input: 0.3,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 2.5,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
    DefaultPricing {
        provider: "Antigravity",
        model: "gemini-2.5-pro",
        input: 1.25,
        cache_read: 0.0,
        cache_write: 0.0,
        output: 10.0,
        batch_input: 0.0,
        batch_output: 0.0,
        currency: "USD",
        source_url: "https://ai.google.dev/gemini-api/docs/pricing",
    },
];

pub fn run_seed(conn: &rusqlite::Connection) -> AppResult<()> {
    for item in DEFAULT_PRICING {
        conn.execute(
            "INSERT INTO model_pricing
                (model, provider, input_price_per_million, cache_read_price_per_million,
                 cache_write_price_per_million, output_price_per_million,
                 batch_input_price_per_million, batch_output_price_per_million,
                 currency, source_url, effective_date, is_default)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
             ON CONFLICT(model) DO UPDATE SET
                 provider = excluded.provider,
                 input_price_per_million = excluded.input_price_per_million,
                 cache_read_price_per_million = excluded.cache_read_price_per_million,
                 cache_write_price_per_million = excluded.cache_write_price_per_million,
                 output_price_per_million = excluded.output_price_per_million,
                 batch_input_price_per_million = excluded.batch_input_price_per_million,
                 batch_output_price_per_million = excluded.batch_output_price_per_million,
                 currency = excluded.currency,
                 source_url = excluded.source_url,
                 effective_date = excluded.effective_date
             WHERE model_pricing.is_default = 1;",
            params![
                item.model,
                item.provider,
                item.input,
                item.cache_read,
                item.cache_write,
                item.output,
                item.batch_input,
                item.batch_output,
                item.currency,
                item.source_url,
                CATALOG_VERSION,
            ],
        )?;
    }
    let placeholders = std::iter::repeat_n("?", DEFAULT_PRICING.len())
        .collect::<Vec<_>>()
        .join(", ");
    conn.execute(
        &format!(
            "DELETE FROM model_pricing WHERE is_default = 1 AND model NOT IN ({placeholders})"
        ),
        params_from_iter(DEFAULT_PRICING.iter().map(|item| item.model)),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::database::schema::create_tables;

    #[test]
    fn seed_adds_catalog_without_overwriting_a_user_rate() {
        let conn = rusqlite::Connection::open_in_memory().unwrap();
        create_tables(&conn).unwrap();
        run_seed(&conn).unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM model_pricing", [], |row| row.get(0))
            .unwrap();
        assert_eq!(count, DEFAULT_PRICING.len() as i64);
        let fable_51: (f64, f64, f64) = conn
            .query_row(
                "SELECT input_price_per_million, cache_read_price_per_million,
                        output_price_per_million
                 FROM model_pricing WHERE model = 'claude-fable-5.1'",
                [],
                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
            )
            .unwrap();
        assert_eq!(fable_51, (10.0, 0.25, 50.0));

        let latest_rows: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM model_pricing
                 WHERE model IN ('gpt-6-astra', 'gemini-3.8-flash', 'qwen3.8-max',
                                 'grok-4.6', 'claude-mythos-5.1')
                   AND effective_date = ?",
                [CATALOG_VERSION],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(latest_rows, 5);

        conn.execute(
            "UPDATE model_pricing SET input_price_per_million = 9 WHERE model = 'gpt-5.6-sol'",
            [],
        )
        .unwrap();
        run_seed(&conn).unwrap();
        let default_price: f64 = conn
            .query_row(
                "SELECT input_price_per_million FROM model_pricing WHERE model = 'gpt-5.6-sol'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(
            default_price, 4.0,
            "shipped rates may update between releases"
        );

        conn.execute(
            "UPDATE model_pricing SET input_price_per_million = 99, is_default = 0 WHERE model = 'gpt-5.6-sol'",
            [],
        )
        .unwrap();
        run_seed(&conn).unwrap();
        let price: f64 = conn
            .query_row(
                "SELECT input_price_per_million FROM model_pricing WHERE model = 'gpt-5.6-sol'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(price, 99.0);
    }

    #[test]
    fn seed_removes_only_stale_default_rows() {
        let conn = rusqlite::Connection::open_in_memory().unwrap();
        create_tables(&conn).unwrap();
        conn.execute(
            "INSERT INTO model_pricing (model, input_price_per_million, output_price_per_million, is_default) VALUES ('retired-default', 1, 1, 1)",
            [],
        ).unwrap();
        conn.execute(
            "INSERT INTO model_pricing (model, input_price_per_million, output_price_per_million, is_default) VALUES ('custom-legacy', 1, 1, 0)",
            [],
        ).unwrap();
        run_seed(&conn).unwrap();
        let retired: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM model_pricing WHERE model = 'retired-default'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        let custom: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM model_pricing WHERE model = 'custom-legacy'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(retired, 0);
        assert_eq!(custom, 1);
    }
}
